version: 2.1

jobs:
  test:
    executor: xcode-10
    steps:
      - setup
      - run: bundle exec pod repo add-cdn jsDelivr-Specs "https://cdn.jsdelivr.net/cocoa/"
      - run: bundle exec pod lib lint --swift-version=4.2 --sources=jsDelivr-Specs
      - run: bundle exec pod lib lint --swift-version=5.0 --sources=jsDelivr-Specs
      - run:
          name: Fastlane Test
          command: |
            cd Example
            bundle exec fastlane test

  carthage-build:
    executor: xcode-10
    steps:
      - setup
      - run:
          name: Update homebrew dependencies
          command: brew update 1> /dev/null 2> /dev/null
      - run:
          name: Update Carthage
          command: brew outdated carthage || (brew uninstall carthage --force; HOMEBREW_NO_AUTO_UPDATE=1 brew install carthage --force-bottle)
      - run:
          name: Build with Carthage
          command: carthage build --no-skip-current && test -d Carthage/Build/iOS/Swiftilities.framework

  deploy-to-cocoapods:
    executor: xcode-10
    steps:
      - setup
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run: bundle exec pod trunk push

executors:
  xcode-10:
    macos:
      xcode: "10.2.1"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -eo pipefail

commands:
  setup:
    description: "Shared setup"
    steps:
      - checkout
      - restore-gems

  restore-gems:
    description: "Restore Ruby Gems"
    steps:
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.5" > ~/.ruby-version
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - carthage-build:
          filters:
            tags:
              only: /.*/
      - deploy-to-cocoapods:
          requires:
            - test
            - carthage-build
          filters:
            tags:
              only: /\d+(\.\d+)*(-.*)*/
            branches:
              ignore: /.*/
